"""Add image_url to products and variants

Revision ID: 4e731569992d
Revises: da1821e27401
Create Date: 2026-08-25 14:31:52.040111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e731569992d'
down_revision: Union[str, None] = 'da1821e27401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    op.drop_column('product_variants', 'image_url')
    # ### end Alembic commands ###
