"""Add indexes for status and category

Revision ID: 68adfab2cbe2
Revises: 420ef5f58cdf
Create Date: 2026-08-26 16:22:19.260585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68adfab2cbe2'
down_revision: Union[str, None] = '420ef5f58cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_order_number', table_name='orders')
    op.create_index('ix_orders_order_number', 'orders', ['order_number'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_order_number', table_name='orders')
    op.create_index('ix_orders_order_number', 'orders', ['order_number'], unique=True)
    # ### end Alembic commands ###
